/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metrics/{metric_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Metric */
        get: operations["get_metric_v1_metrics__metric_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metrics/{metric_id}/national": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get National Metric */
        get: operations["get_national_metric_v1_metrics__metric_id__national_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/provenance/{metric_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Provenance */
        get: operations["get_provenance_v1_provenance__metric_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/simulations/debtlab": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Debtlab Scenario */
        post: operations["create_debtlab_scenario_v1_simulations_debtlab_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/simulations/debtlab/suggested-assumptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Suggested Assumptions */
        get: operations["get_suggested_assumptions_v1_simulations_debtlab_suggested_assumptions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/simulations/debtlab/{scenario_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Debtlab Scenario */
        get: operations["get_debtlab_scenario_v1_simulations_debtlab__scenario_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssumptionDistributionInput */
        AssumptionDistributionInput: {
            /**
             * Mean
             * @description Fraction, e.g. 0.10 for 10%, not 10
             */
            mean: number;
            /**
             * Std
             * @description Standard deviation, same unit as mean
             */
            std: number;
        };
        /**
         * DataClass
         * @enum {string}
         */
        DataClass: "observed" | "estimated" | "simulated";
        /** DebtLabScenarioBase */
        DebtLabScenarioBase: {
            /**
             * Divida Pib Pct
             * @description Real observed value at reference_date
             */
            divida_pib_pct: number;
            /**
             * Reference Date
             * @description Most recent real divida_bruta_pib period used
             */
            reference_date: string;
            /**
             * Source
             * @description URL of the source series (BCB SGS 13762)
             */
            source: string;
        };
        /** DebtLabScenarioRequest */
        DebtLabScenarioRequest: {
            crescimento_nominal_pib: components["schemas"]["AssumptionDistributionInput"];
            /**
             * Horizon Years
             * @default 10
             */
            horizon_years: number;
            juros_nominal: components["schemas"]["AssumptionDistributionInput"];
            /**
             * N Iterations
             * @default 5000
             */
            n_iterations: number;
            primario_pct_pib: components["schemas"]["AssumptionDistributionInput"];
            /**
             * Seed
             * @default 42
             */
            seed: number;
        };
        /** DebtLabScenarioResponse */
        DebtLabScenarioResponse: {
            assumptions: components["schemas"]["DebtLabScenarioRequest"];
            base: components["schemas"]["DebtLabScenarioBase"];
            /** Created At */
            created_at: string;
            /** @default simulated */
            data_class: components["schemas"]["DataClass"];
            /** Deterministic Trajectory */
            deterministic_trajectory: components["schemas"]["YearlyDeterministic"][];
            /** Engine Version */
            engine_version: string;
            /** Horizon Years */
            horizon_years: number;
            /** N Iterations */
            n_iterations: number;
            /** Percentiles */
            percentiles: components["schemas"]["YearlyPercentiles"][];
            /** Scenario Id */
            scenario_id: string;
            /** Seed */
            seed: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MetricResponse */
        MetricResponse: {
            data_class: components["schemas"]["DataClass"];
            /** Metric Id */
            metric_id: string;
            provenance: components["schemas"]["ProvenanceSummary"];
            /** Reference Date */
            reference_date: string;
            /** Reference Year */
            reference_year: number;
            /** State Ibge Code */
            state_ibge_code: string;
            /** Unit */
            unit: string;
            /** Value */
            value: number;
        };
        /** NationalMetricResponse */
        NationalMetricResponse: {
            data_class: components["schemas"]["DataClass"];
            /** Metric Id */
            metric_id: string;
            provenance: components["schemas"]["ProvenanceSummary"];
            /** Reference Date */
            reference_date: string;
            /** Unit */
            unit: string;
            /** Value */
            value: number;
        };
        /** ProvenanceResponse */
        ProvenanceResponse: {
            /** Bronze Object */
            bronze_object: string;
            /** Catalog Dataset Id */
            catalog_dataset_id: string;
            /** Gold Object */
            gold_object: string;
            /** Metric Id */
            metric_id: string;
            /** Producing Organization */
            producing_organization: string;
            /** Reference Date */
            reference_date: string;
            /** Reference Year */
            reference_year: number;
            /** Silver Transform */
            silver_transform: string;
            /** Silver Transform Version */
            silver_transform_version: string;
            /** Source Resource Url */
            source_resource_url: string;
            /** State Ibge Code */
            state_ibge_code: string;
            /** Trust Status */
            trust_status: string;
        };
        /** ProvenanceSummary */
        ProvenanceSummary: {
            /** Reference Date */
            reference_date: string;
            /**
             * Source
             * @description URL of the source resource
             */
            source: string;
            /**
             * Trust Status
             * @description Provenance trust status; 'source_only' until a Data Trust Score exists (SPEC-006)
             */
            trust_status: string;
        };
        /** SuggestedAssumption */
        SuggestedAssumption: {
            /**
             * Mean
             * @description Fraction, e.g. 0.10 for 10%, not 10
             */
            mean: number;
            /**
             * Methodology
             * @description Plain-text note on how mean/std were derived from the real series
             */
            methodology: string;
            /** Period End */
            period_end: string;
            /** Period Start */
            period_start: string;
            /**
             * Source Metric Id
             * @description Gold metric_id the suggestion was derived from
             */
            source_metric_id: string;
            /**
             * Std
             * @description Standard deviation, same unit as mean
             */
            std: number;
            /**
             * Window Months
             * @description Number of real trailing months used
             */
            window_months: number;
        };
        /** SuggestedAssumptionsResponse */
        SuggestedAssumptionsResponse: {
            crescimento_nominal_pib: components["schemas"]["SuggestedAssumption"];
            /** @default estimated */
            data_class: components["schemas"]["DataClass"];
            juros_nominal: components["schemas"]["SuggestedAssumption"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** YearlyDeterministic */
        YearlyDeterministic: {
            /** Divida Pib Pct */
            divida_pib_pct: number;
            /** Year Offset */
            year_offset: number;
        };
        /** YearlyPercentiles */
        YearlyPercentiles: {
            /** P10 */
            p10: number;
            /** P25 */
            p25: number;
            /** P50 */
            p50: number;
            /** P75 */
            p75: number;
            /** P90 */
            p90: number;
            /** Year Offset */
            year_offset: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_metric_v1_metrics__metric_id__get: {
        parameters: {
            query?: {
                state_ibge_code?: string | null;
            };
            header?: never;
            path: {
                metric_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_national_metric_v1_metrics__metric_id__national_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                metric_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NationalMetricResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_provenance_v1_provenance__metric_id__get: {
        parameters: {
            query?: {
                state_ibge_code?: string | null;
            };
            header?: never;
            path: {
                metric_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvenanceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_debtlab_scenario_v1_simulations_debtlab_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DebtLabScenarioRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebtLabScenarioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_suggested_assumptions_v1_simulations_debtlab_suggested_assumptions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestedAssumptionsResponse"];
                };
            };
        };
    };
    get_debtlab_scenario_v1_simulations_debtlab__scenario_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebtLabScenarioResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
