/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metrics/{metric_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Metric */
        get: operations["get_metric_v1_metrics__metric_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/provenance/{metric_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Provenance */
        get: operations["get_provenance_v1_provenance__metric_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * DataClass
         * @enum {string}
         */
        DataClass: "observed" | "estimated" | "simulated";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MetricResponse */
        MetricResponse: {
            data_class: components["schemas"]["DataClass"];
            /** Metric Id */
            metric_id: string;
            provenance: components["schemas"]["ProvenanceSummary"];
            /** Reference Date */
            reference_date: string;
            /** Reference Year */
            reference_year: number;
            /** State Ibge Code */
            state_ibge_code: string;
            /** Unit */
            unit: string;
            /** Value */
            value: number;
        };
        /** ProvenanceResponse */
        ProvenanceResponse: {
            /** Bronze Object */
            bronze_object: string;
            /** Catalog Dataset Id */
            catalog_dataset_id: string;
            /** Gold Object */
            gold_object: string;
            /** Metric Id */
            metric_id: string;
            /** Producing Organization */
            producing_organization: string;
            /** Reference Date */
            reference_date: string;
            /** Reference Year */
            reference_year: number;
            /** Silver Transform */
            silver_transform: string;
            /** Silver Transform Version */
            silver_transform_version: string;
            /** Source Resource Url */
            source_resource_url: string;
            /** State Ibge Code */
            state_ibge_code: string;
            /** Trust Status */
            trust_status: string;
        };
        /** ProvenanceSummary */
        ProvenanceSummary: {
            /** Reference Date */
            reference_date: string;
            /**
             * Source
             * @description URL of the source resource
             */
            source: string;
            /**
             * Trust Status
             * @description Provenance trust status; 'source_only' until a Data Trust Score exists (SPEC-006)
             */
            trust_status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_metric_v1_metrics__metric_id__get: {
        parameters: {
            query?: {
                state_ibge_code?: string | null;
            };
            header?: never;
            path: {
                metric_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_provenance_v1_provenance__metric_id__get: {
        parameters: {
            query?: {
                state_ibge_code?: string | null;
            };
            header?: never;
            path: {
                metric_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvenanceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
